#!/bin/bash

# -------------------------
# Filename: KLEE_Seed_Parse.py
# Revision: 1.0
# Data:     2018/11/29
# Author:   Yue Cao
# Description:  Parse the result in Seed_Temp, which is generated by KLEE_Seed_Generation

import sys

file1 = sys.argv[1]
file2 = sys.argv[2]
#f1 = file("Seed_Temp.txt", "r")
#f2 = file("Seed_Temp2.txt", "w")
f1 = file(file1, "r")
f2 = file(file2, "w")

found = False
for line in f1:
    if found:
        if line.find("KLEE INPUT") != -1:
            found = False
            continue
        f2.write(line)
    elif line.find("KLEE INPUT") != -1:
        found = True
